# Generated by nitcc for the language re_parser

# Standalone parser tester for the language re_parser
module re_parser_test_parser
import nitcc_runtime
import re_parser_lexer
import re_parser_parser

# Class to test the parser for the language re_parser
class TestParser_re_parser
	super TestParser
	redef fun name do return "re_parser"
	redef fun new_lexer(text) do return new Lexer_re_parser(text)
	redef fun new_parser do return new Parser_re_parser
end
var t = new TestParser_re_parser
t.main
