#include "nit.common.h"
extern const int COLOR_core__abstract_text__Text__to_cstring;
char* core__environ___CString___get_environ(char* self);
val* core__flat___CString___to_s_unsafe(char* self, val* p0, val* p1, val* p2, val* p3);
val* core__flat___CString___core__abstract_text__Object__to_s(char* self);
void core__environ___CString___setenv(char* self, char* p0);
extern const int COLOR_core__environ__String__environ;
extern const int COLOR_core__string_search__Text__split;
extern const int COLOR_core__abstract_collection__Collection__iterator;
extern const int COLOR_core__abstract_collection__Iterator__is_ok;
extern const int COLOR_core__abstract_collection__Iterator__item;
extern const int COLOR_core__file__Text__file_exists;
extern const int COLOR_core__file__String__join_path;
extern const int COLOR_core__abstract_collection__Iterator__next;
extern const int COLOR_core__abstract_collection__Iterator__finish;
char* core__environ___CString_get_environ___impl( char* self );
void core__environ___CString_setenv___impl( char* self, char* value );
extern const int COLOR_core__environ___Sys___core__kernel__Object__init;
extern const int COLOR_core__kernel__Object___33d_61d;
extern const int COLOR_core__abstract_text__Text__to_i;
extern const int COLOR_core__math__Sys__srand_from;
