#include "nit.common.h"
val* NEW_nitcc__Gram(const struct type* type);
extern const struct type type_nitcc__Gram;
extern const int COLOR_core__kernel__Object__init;
val* NEW_nitcc__Production(const struct type* type);
extern const struct type type_nitcc__Production;
val* core__flat___CString___to_s_unsafe(char* self, val* p0, val* p1, val* p2, val* p3);
extern const int COLOR_nitcc__grammar__Element__name_61d;
extern const int COLOR_nitcc__grammar__Gram__prods;
val* NEW_core__Array(const struct type* type);
extern const struct type type_core__Array__nitcc__Production;
extern const int COLOR_core__array__Array__with_capacity;
extern const int COLOR_core__abstract_collection__Sequence__push;
extern const int COLOR_core__abstract_collection__SimpleCollection__add_all;
extern const int COLOR_core__abstract_collection__SimpleCollection__add;
val* NEW_nitcc__Token(const struct type* type);
extern const struct type type_nitcc__Token;
extern const int COLOR_nitcc__grammar__Gram__tokens;
extern const struct type type_core__Array__nitcc__Token;
extern const struct type type_core__Array__nitcc__Element;
val* NEW_core__NativeArray(int length, const struct type* type);
extern const struct type type_core__NativeArray__nitcc__Element;
extern const int COLOR_core__array__Array__with_native;
extern const int COLOR_nitcc__grammar__Production__new_alt;
extern const int COLOR_nitcc__grammar__Production__new_alt0;
extern const int COLOR_nitcc__grammar__Alternative__phony_61d;
extern const int COLOR_nitcc__grammar__Gram__lr0;
extern const struct type type_core__NativeArray__core__String;
extern const int COLOR_nitcc__grammar__LRAutomaton__states;
extern const int COLOR_core__abstract_collection__Collection__length;
val* core__flat___Int___core__abstract_text__Object__to_s(long self);
extern const int COLOR_core__abstract_text__NativeArray__native_to_s;
extern const int COLOR_core__file__Sys__print;
extern const int COLOR_nitcc__grammar__LRAutomaton__to_dot;
extern const int COLOR_nitcc__grammar__LRAutomaton__gen_to_nit;
val* NEW_core__FileWriter(const struct type* type);
extern const struct type type_core__FileWriter;
extern const int COLOR_core__file__FileWriter__open;
extern const int COLOR_core__stream__Writer__write;
extern const int COLOR_core__stream__Stream__close;
