#include "nit.common.h"
#define COLOR_serialization__caching__CachingSerializer___cache 0
extern const char FILE_serialization__caching[];
val* NEW_serialization__SerializerCache(const struct type* type);
extern const struct type type_serialization__SerializerCache;
#define COLOR_serialization__caching__SerializerCache___sent 0
#define COLOR_core__abstract_collection__MapRead__keys 20
#define COLOR_core__abstract_collection__Collection__has 30
#define COLOR_core__abstract_collection__MapRead___91d_93d 18
long serialization___serialization__SerializerCache___next_available_id(val* self);
#define COLOR_core__abstract_collection__Map___91d_93d_61d 25
#define COLOR_core__abstract_collection__MapRead__length 15
